### ISSUE TITLE
roll an 0.3.0 release

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-compat#180]
needed over at https://github.com/scala/community-builds/pull/849

**Comment by SethTisue** [comment]
tagged, release notes attached: https://github.com/scala/scala-collection-compat/releases/tag/v0.2.2

**Comment by SethTisue** [comment]
Travis publishing run: https://travis-ci.org/scala/scala-collection-compat/builds/490341153

**Comment by SethTisue** [comment]
the 6 staging repos on oss.sonatype.org are orgscala-lang-1664 through orgscala-lang-1669. I hit "close" and "release" on them

**Comment by SethTisue** [comment]
gah, 2.11 artifacts aren't on Maven Central

**Comment by SethTisue** [comment]
haha well no wonder, wtf

```
  exclude:
    # ?                                                                                                                
    - jdk: oraclejdk8
      scala: 2.11.12
```
